use super::CourtArea;
use std::collections::HashSet;
use std::sync::LazyLock;

/// Court movement graph stored as adjacency data.
/// This replaces the 250+ line match statement with a data-driven approach.
static COURT_GRAPH: LazyLock<Vec<(CourtArea, &'static [CourtArea])>> = LazyLock::new(|| {
    vec![
        (
            CourtArea::Basket,
            &[
                CourtArea::RestrictedAreaMiddle,
                CourtArea::RestrictedAreaRight,
                CourtArea::RestrictedAreaLeft,
            ],
        ),
        (
            CourtArea::RestrictedAreaLeft,
            &[
                CourtArea::RestrictedAreaLeft,
                CourtArea::RestrictedAreaMiddle,
                CourtArea::LowPostLeft,
                CourtArea::ShortCornerLeft,
                CourtArea::ElbowLeft,
                CourtArea::FreeThrowLine,
                CourtArea::Basket,
            ],
        ),
        (
            CourtArea::RestrictedAreaMiddle,
            &[
                CourtArea::RestrictedAreaLeft,
                CourtArea::RestrictedAreaMiddle,
                CourtArea::RestrictedAreaRight,
                CourtArea::LowPostLeft,
                CourtArea::LowPostRight,
                CourtArea::ElbowLeft,
                CourtArea::ElbowRight,
                CourtArea::FreeThrowLine,
                CourtArea::Basket,
            ],
        ),
        (
            CourtArea::RestrictedAreaRight,
            &[
                CourtArea::RestrictedAreaMiddle,
                CourtArea::RestrictedAreaRight,
                CourtArea::LowPostRight,
                CourtArea::ShortCornerRight,
                CourtArea::ElbowRight,
                CourtArea::FreeThrowLine,
                CourtArea::Basket,
            ],
        ),
        (
            CourtArea::LowPostLeft,
            &[
                CourtArea::RestrictedAreaLeft,
                CourtArea::RestrictedAreaMiddle,
                CourtArea::LowPostLeft,
                CourtArea::ShortCornerLeft,
                CourtArea::ElbowLeft,
                CourtArea::MidrangeBaselineLeft,
                CourtArea::MidrangeWingLeft,
            ],
        ),
        (
            CourtArea::LowPostRight,
            &[
                CourtArea::RestrictedAreaRight,
                CourtArea::RestrictedAreaMiddle,
                CourtArea::LowPostRight,
                CourtArea::ShortCornerRight,
                CourtArea::ElbowRight,
                CourtArea::MidrangeBaselineRight,
                CourtArea::MidrangeWingRight,
            ],
        ),
        (
            CourtArea::ShortCornerLeft,
            &[
                CourtArea::RestrictedAreaLeft,
                CourtArea::ShortCornerLeft,
                CourtArea::ElbowLeft,
                CourtArea::MidrangeBaselineLeft,
            ],
        ),
        (
            CourtArea::ShortCornerRight,
            &[
                CourtArea::RestrictedAreaRight,
                CourtArea::ShortCornerRight,
                CourtArea::ElbowRight,
                CourtArea::MidrangeBaselineRight,
            ],
        ),
        (
            CourtArea::ElbowLeft,
            &[
                CourtArea::RestrictedAreaLeft,
                CourtArea::RestrictedAreaMiddle,
                CourtArea::ElbowLeft,
                CourtArea::FreeThrowLine,
                CourtArea::MidrangeWingLeft,
                CourtArea::MidrangeBaselineLeft,
                CourtArea::MidrangeCenter,
            ],
        ),
        (
            CourtArea::ElbowRight,
            &[
                CourtArea::RestrictedAreaRight,
                CourtArea::RestrictedAreaMiddle,
                CourtArea::ElbowRight,
                CourtArea::FreeThrowLine,
                CourtArea::MidrangeWingRight,
                CourtArea::MidrangeBaselineRight,
                CourtArea::MidrangeCenter,
            ],
        ),
        (
            CourtArea::FreeThrowLine,
            &[
                CourtArea::RestrictedAreaLeft,
                CourtArea::RestrictedAreaMiddle,
                CourtArea::RestrictedAreaRight,
                CourtArea::FreeThrowLine,
                CourtArea::LowPostLeft,
                CourtArea::LowPostRight,
                CourtArea::ElbowLeft,
                CourtArea::ElbowRight,
                CourtArea::MidrangeWingLeft,
                CourtArea::MidrangeWingRight,
                CourtArea::MidrangeCenter,
            ],
        ),
        (
            CourtArea::MidrangeBaselineLeft,
            &[
                CourtArea::MidrangeBaselineLeft,
                CourtArea::ShortCornerLeft,
                CourtArea::LowPostLeft,
                CourtArea::ElbowLeft,
                CourtArea::MidrangeWingLeft,
                CourtArea::ThreePointLineCornerLeft,
            ],
        ),
        (
            CourtArea::MidrangeBaselineRight,
            &[
                CourtArea::MidrangeBaselineRight,
                CourtArea::ShortCornerRight,
                CourtArea::LowPostRight,
                CourtArea::ElbowRight,
                CourtArea::MidrangeWingRight,
                CourtArea::ThreePointLineCornerRight,
            ],
        ),
        (
            CourtArea::MidrangeWingLeft,
            &[
                CourtArea::MidrangeWingLeft,
                CourtArea::MidrangeCenter,
                CourtArea::MidrangeBaselineLeft,
                CourtArea::FreeThrowLine,
                CourtArea::ElbowLeft,
                CourtArea::LowPostLeft,
                CourtArea::ThreePointLineWingLeft,
                CourtArea::ThreePointLineCenter,
            ],
        ),
        (
            CourtArea::MidrangeWingRight,
            &[
                CourtArea::MidrangeWingRight,
                CourtArea::MidrangeCenter,
                CourtArea::MidrangeBaselineRight,
                CourtArea::FreeThrowLine,
                CourtArea::ElbowRight,
                CourtArea::LowPostRight,
                CourtArea::ThreePointLineWingRight,
                CourtArea::ThreePointLineCenter,
            ],
        ),
        (
            CourtArea::MidrangeCenter,
            &[
                CourtArea::MidrangeCenter,
                CourtArea::MidrangeWingLeft,
                CourtArea::MidrangeWingRight,
                CourtArea::ThreePointLineWingLeft,
                CourtArea::ThreePointLineWingRight,
                CourtArea::ThreePointLineCenter,
                CourtArea::ElbowLeft,
                CourtArea::ElbowRight,
                CourtArea::FreeThrowLine,
            ],
        ),
        (
            CourtArea::ThreePointLineCornerLeft,
            &[
                CourtArea::ThreePointLineCornerLeft,
                CourtArea::ThreePointLineWingLeft,
                CourtArea::MidrangeBaselineLeft,
                CourtArea::MidrangeWingLeft,
            ],
        ),
        (
            CourtArea::ThreePointLineCornerRight,
            &[
                CourtArea::ThreePointLineCornerRight,
                CourtArea::ThreePointLineWingRight,
                CourtArea::MidrangeBaselineRight,
                CourtArea::MidrangeWingRight,
            ],
        ),
        (
            CourtArea::ThreePointLineWingLeft,
            &[
                CourtArea::ThreePointLineWingLeft,
                CourtArea::ThreePointLineCenter,
                CourtArea::MidrangeWingLeft,
                CourtArea::MidrangeCenter,
                CourtArea::MidrangeBaselineLeft,
                CourtArea::ThreePointLineCornerLeft,
            ],
        ),
        (
            CourtArea::ThreePointLineWingRight,
            &[
                CourtArea::ThreePointLineWingRight,
                CourtArea::ThreePointLineCenter,
                CourtArea::MidrangeWingRight,
                CourtArea::MidrangeCenter,
                CourtArea::MidrangeBaselineRight,
                CourtArea::ThreePointLineCornerRight,
            ],
        ),
        (
            CourtArea::ThreePointLineCenter,
            &[
                CourtArea::ThreePointLineCenter,
                CourtArea::ThreePointLineWingLeft,
                CourtArea::ThreePointLineWingRight,
                CourtArea::MidrangeWingLeft,
                CourtArea::MidrangeWingRight,
                CourtArea::MidrangeCenter,
                CourtArea::Center,
            ],
        ),
        (
            CourtArea::Center,
            &[
                CourtArea::Center,
                CourtArea::ThreePointLineCenter,
                CourtArea::ThreePointLineWingLeft,
                CourtArea::ThreePointLineWingRight,
                CourtArea::Backcourt,
            ],
        ),
        (
            CourtArea::Backcourt,
            &[
                CourtArea::Backcourt,
                CourtArea::Center,
                CourtArea::ThreePointLineWingLeft,
                CourtArea::ThreePointLineWingRight,
            ],
        ),
        (
            CourtArea::SidelineLeft,
            &[
                CourtArea::SidelineLeft,
                CourtArea::ThreePointLineCornerLeft,
                CourtArea::ThreePointLineWingLeft,
                CourtArea::MidrangeWingLeft,
                CourtArea::MidrangeBaselineLeft,
            ],
        ),
        (
            CourtArea::SidelineRight,
            &[
                CourtArea::SidelineRight,
                CourtArea::ThreePointLineCornerRight,
                CourtArea::ThreePointLineWingRight,
                CourtArea::MidrangeBaselineRight,
                CourtArea::MidrangeWingRight,
            ],
        ),
        (
            CourtArea::BaselineLeft,
            &[
                CourtArea::BaselineLeft,
                CourtArea::LowPostLeft,
                CourtArea::ShortCornerLeft,
                CourtArea::MidrangeBaselineLeft,
                CourtArea::RestrictedAreaLeft,
                CourtArea::RestrictedAreaMiddle,
            ],
        ),
        (
            CourtArea::BaselineRight,
            &[
                CourtArea::BaselineRight,
                CourtArea::LowPostRight,
                CourtArea::ShortCornerRight,
                CourtArea::MidrangeBaselineRight,
                CourtArea::RestrictedAreaRight,
                CourtArea::RestrictedAreaMiddle,
            ],
        ),
        (CourtArea::OutOfBounds, &[CourtArea::OutOfBounds]),
    ]
});

/// Returns the set of court areas that can be reached from the current area.
pub fn can_move_to(current_area: CourtArea) -> HashSet<CourtArea> {
    COURT_GRAPH
        .iter()
        .find(|(area, _)| *area == current_area)
        .map(|(_, neighbors)| neighbors.iter().copied().collect())
        .unwrap_or_else(|| HashSet::from([current_area]))
}
